baseURL = "https://parrotsky.github.io"
theme = "hugo-bearcub"
copyright = "GoodGoodSky"
defaultContentLanguage = "en"
enableRobotsTXT = true
enableEmoji = true
defaultContentLanguageInSubdir = true
enableGitInfo = false

# Setup syntax highlighting without inline styles
[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    noClasses = false

# Multilingual mode config
[languages]
  [languages.en]
    contentDir = "content/en"
    languageCode = "en-US"
    languageDirection = "ltr"
    languageName = "English"
    title = "Yue" # Shown on the home page
    weight = 10
    [languages.en.menus]
      [[languages.en.menus.main]]
        name = "Home"
        pageRef = "/"
        weight = 10
      [[languages.en.menus.main]]
        name = "Posts"
        pageRef = "/posts"
        weight = 20
      [[languages.en.menus.main]]
        name = "Tags"
        pageRef = "/tags"
        weight = 30
      [[languages.en.menus.main]]
        name = "Categories"
        pageRef = "/categories"
        weight = 40
      [[languages.en.menus.main]]
        name = "About"
        pageRef = "/about"
        weight = 50
    [languages.en.params]
      dateFormat = "Jan 02, 2006"
      author = "Jane Doe"
      [languages.en.params.footer]
        copyrightYearStart = 2023
        copyrightYearEnd = 2024
        author = "Jane Doe"

  [languages.zh-CN]
    hasCJKLanguage = true
    contentDir = "content/zh-CN"
    languageCode = "zh-CN"
    languageDirection = "ltr"
    languageName = "中文"
    title = "月"
    weight = 20
    [languages.zh-CN.menus]
      [[languages.zh-CN.menus.main]]
        name = "主页"
        pageRef = "/"
        weight = 10
      [[languages.zh-CN.menus.main]]
        name = "文章"
        pageRef = "/posts"
        weight = 20
      [[languages.zh-CN.menus.main]]
        name = "标签"
        pageRef = "/tags"
        weight = 30
      [[languages.zh-CN.menus.main]]
        name = "类别"
        pageRef = "/categories"
        weight = 40
      [[languages.zh-CN.menus.main]]
        name = "关于"
        pageRef = "/about"
        weight = 50
    [languages.zh-CN.params]
      dateFormat = "2006年1月02日"
      author = "小月"
      [languages.zh-CN.params.footer]
        copyrightYearStart = 2023
        author = "小月"

[params]
  # The description of your website
  description = "Bear Cub Demo"
  # The path to your favicon
  favicon = "images/favicon.png"
  # These images will show up when services want to generate a preview of a link to your site
  images = ["images/share.webp"]
  # This title is used as the site_name on the Hugo's internal opengraph structured data template
  title = "Bear Cub"
  # Dates are displayed following the format below
  dateFormat = "2006-01-02"
  # If your blog is multilingual but you haven't translated a page, this theme will create a disabled link
  hideUntranslated = false
  # CSS styles options: "original" or "herman"
  themeStyle = "original"
  # Generate social cards for posts without `images` defined in their front matter
  generateSocialCard = true
  # Social media metadata
  [params.social]
    twitter = "example" # Twitter handle (without '@')
    facebook_admin = "0000000000" # Facebook Page Admin ID
  # Author metadata
  [params.author]
    name = "John Doe" # Your name as shown in the RSS feed metadata
    email = "me@example.com" # Added to the footer so readers can reply to posts

# Frontmatter configuration
[frontmatter]
  lastmod = ['lastmod', ':default'] # lastmod in front matter has highest precedence

# Markup configuration
[markup.goldmark.renderer]
  unsafe = true # Allow HTML code in Markdown
